Handle China National Day
kylekatarnls/business-day pull request #59
Opened 2021-01-07 14:16 UTC by kylekatarnls

Partial fix for #58

2021-01-11 01:37 UTC, liuyong888 requested changes
@kylekatarnls

2021-01-11 08:30 UTC, kylekatarnls commented on src/Cmixin/Holidays/cn-national.php
> +    '08-01-12:00'                => '= 08-01 12:00',
Setting `'08-01-12:00' => null` make `isHoliday()` false, but `isWeekend()` will still be true, so `isBusinessDay()` should still be false if it's in the week-end.

But as it's not officially holiday, it's relevant to remove it.

2021-01-11 08:54 UTC, liuyong888 commented on src/Cmixin/Holidays/cn-national.php
> +    '03-08-12:00'                => '= 03-08 12:00',
03-08-12:00 Remove it!

2021-01-11 09:06 UTC, liuyong888 commented
When will it be merged into the master branch?
Thanks!
@kylekatarnls

2021-01-17 00:41 UTC, merged

2021-01-17 00:42 UTC, kylekatarnls commented
You can now check the new list on `dev-master` version.