refresh ar-national to 2021
kylekatarnls/business-day pull request #66
Opened 2021-02-03 23:26 UTC by mpoma

2021-02-03 23:28 UTC, mpoma commented
I refresh Argentina national holidays to 2021

2021-02-04 08:50 UTC, kylekatarnls requested changes
Thanks 🙏

2021-02-04 08:50 UTC, kylekatarnls commented on src/Cmixin/Holidays/ar-national.php
> +    'substitutes-day-of-respect-for-cultural-diversity'  => '10-08',    //especial day for 2021
If it won't be holiday on next years, precise the year:
```suggestion
    'substitutes-day-of-respect-for-cultural-diversity'  => '2021-10-08',    //especial day for 2021
```

2021-02-04 08:50 UTC, kylekatarnls commented on src/Cmixin/Holidays/ar-national.php
> +    'substitutes-soberany-day'                           => '11-22',    //especial day for 2021
```suggestion
    'substitutes-soberany-day'                           => '2021-11-22',    //especial day for 2021
```

2021-02-04 13:23 UTC, kylekatarnls reviewed
I will check #65 then come back to this.

2021-02-04 13:24 UTC, kylekatarnls approved these changes

2021-02-06 13:25 UTC, merged